# Generated by Django 5.1.3 on 2024-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(default='Sophia Alexis', max_length=50)),
                ('category', models.CharField(default='clothing', max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=19.99, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_six', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
